import Link from "next/link";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-sans">
        <nav className="px-20 bg-gray-900 text-white p-4 shadow-md">
          <ul className="flex">
            <li>
              <Link href="/" className="hover:bg-gray-800 px-6 py-4 transition duration-200"
              >
                Home
              </Link>
            </li>
            <li>
              <Link href="/about" className="hover:bg-gray-800 px-6 py-4 transition duration-200">
                About
              </Link>
            </li>
            <li>
              <Link href="/form" className="hover:bg-gray-800 px-6 py-4 transition duration-200">
                Form
              </Link>
            </li>
          </ul>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
